# Generated by Django 5.2.1 on 2025-05-31 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_stock_warehouse_stockitem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='product',
            name='category_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='pos.product'),
        ),
    ]
