# Generated by Django 5.2.1 on 2025-05-31 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_alter_stockitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='percentage',
            field=models.FloatField(default=0.0),
        ),
    ]
