# Generated by Django 5.2.1 on 2025-06-02 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_warehouse_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_id_backend',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category_id_backend',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='product_id_backend',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='pos.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_deleted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='pos.subcategory'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
