# Generated by Django 5.2.1 on 2025-06-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_remove_product_category_id_backend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='marge',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
