# Generated by Django 5.2.1 on 2025-06-08 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_alter_product_marge'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='pos.variant'),
        ),
    ]
